# Generated by Django 5.0.6 on 2024-06-17 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppUser',
        ),
    ]
