# Generated by Django 5.0.6 on 2024-07-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
